### ISSUE TITLE
Add a feed?

### ISSUE THREAD

**Issue by tfausak** [adamwespiser/wespiser.com#1]
Hi! I am the editor of [Haskell Weekly](https://haskellweekly.news). I would like to be notified when you publish a new post, but as far as I can tell your site does not have a feed. Would you mind adding an Atom or RSS feed? Thanks!

**Comment by adamwespiser** [comment]
Hi @tfausak! Thanks for reaching out! I've recently updated the site, in anticipation of some new Haskell articles. (https://www.wespiser.com) 
Per your ticket, I've added RSS and Atom Feed:

- Atom: http://www.wespiser.com/feed.atom
- RSS: http://www.wespiser.com/feed.rss

**Comment by tfausak** [comment]
Perfect, thanks!
